"""add previous_version_id and is_superseded to knowledge_source_versions

Revision ID: d07efef38734
Revises: 0001
Create Date: 2026-09-20 17:55:04.779399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd07efef38734'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_source_versions', sa.Column('previous_version_id', sa.Uuid(), nullable=True))
    op.add_column('knowledge_source_versions', sa.Column('is_superseded', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_ksv_previous_version', 'knowledge_source_versions', 'knowledge_source_versions', ['previous_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ksv_previous_version', 'knowledge_source_versions', type_='foreignkey')
    op.drop_column('knowledge_source_versions', 'is_superseded')
    op.drop_column('knowledge_source_versions', 'previous_version_id')
    # ### end Alembic commands ###
